### PR TITLE
Add option to display undefined keys as null in Get

### PR DESCRIPTION
**Pull request by DavidFengg**
Example:
```json
"a":[{"x": 1}, {}]
```
When ```EnableUndefined = true``` , an expression such as ```$.a[:].x``` will result in ```[1,"null"]``` instead of ```[1]```

### CODE REVIEW

**Comment by ohler55** [comment]
Let's discuss this a bit further. I have a couple of concerns with this feature.

The first one is adding a global variable to the package introduces a number of issue in itself. The first being that it is no concurrent safe. The second is that if more than one other package is using the jp package the setting of the global will effect all users of the package.

The second concern is that introducing this to just the Get() function makes the First() function behaviour inconsistent with the Get(). The problem with making the First() consistent of course is that nil can be returned instead of an actual value which is probably not what most people would expect.

I suspect the description above was not actually what you intended as the changes you made would result in `[1,null]` and not an array with a `"null"` string.

So, the question is how do we get the behaviour you are looking for and still satisfy those concerns.

One thought would be to have a function that calls the path `$.a[*]` and then apply `$.x` to each result.

**Comment by DavidFengg** [comment]
Thanks for the quick response. To address your concerns,

I can see how a package level variable may not be ideal given the issues. What are your thoughts on having this instead be passed as an option?

Towards your second concern, our use case would intend the possibility of nil being returned first rather than an actual value so a similar change would be needed so that Get() and First() are consistent. First() would reference the most immediate Expr, rather than the first non-null. I believe this strays away from regular jsonpath behaviour, but considering this enabled as an option, would it suffice to just document this change in behaviour?

In regards to our use case, we're parsing table oriented json data. We need undefined values per "record" so our rows aren't misaligned. Ex:
```
[{
  "y": 1,
},{
  "x": 2,
  "y": 3,
},{
  "x": 4,
}]
```
Would result in a table such as
```
x, y
 , 1
2, 3
4, 
```

I think in order to remove the need of a global variable, we would need to add additional state onto the Expr type which can then forth be checked by First() and Get(). This would result in a significant refactor, do you think this would be a good approach?

**Comment by ohler55** [comment]
Honestly, given that getting what you want is only a few lines of code with the existing package it seems like the hard way around by trying to come up with a one line solution by extending the jp package, This is what I would do:

```golang
var table interface{}
for _, x := range jp.C("a").W().Get(data) {
    table = append(table, jp.C("x").First(x))
}
```

There may be a syntax error in there. I did not run it but it should give you the idea. I also uses the non-parsed options to avoid extra error checks.

**Comment by DavidFengg** [comment]
Appreciate the suggested code. The approach you have here works well with the example above but I'll have to do some further testing with more complex json data.

Seems that the our changes may not fit well so I'll be closing the PR on that note. Thank you for your efforts.

**Pull request closed without merging**
