### PR TITLE
Fix nested objects for Builder

### PR DESCRIPTION
**Pull request by nono**
I have made a fix for #95. I have also added a test with fuzzing. Feel free to take only the first commit if you are not interested by the fuzzing.

### CODE REVIEW

**Comment by ohler55** [comment]
I was offline for a bit when I created a different fix in the object-pop branch. I'll take a look at your approach before merging though.

**Comment by ohler55** [comment]
I'd prefer not to defer the creation of the maps until a pop as it needlessly grows the stack. If it made sense to make a map of a preallocated size maybe using the stack to stage the map creation would make sense. I think the approach taken in the object-pop branch is simpler and more efficient although I have not run a benchmark comparison so I may be wrong..

If you don't mind I would like to cherry pick and add your fuzz tests though. It would be a nice addition.

**Comment by nono** [comment]
Your branch `object-pop` works fine for me. And you can cherry-pick my fuzz tests. Feel free to do whatever you think is best.

**Comment by ohler55** [comment]
Thank you. I would be glad to consider any other PR you offer in the future.

**Pull request closed without merging**
